#!/bin/bash
# Fake Plesk CLI: records every call. Failure switches: /tmp/plesk-fail-php (php handler), /tmp/plesk-fail-rename (rename),
# /tmp/plesk-keep-dir (rename "succeeds" but the vhost folder does not move).
echo "$*" >> /tmp/plesk.log
case "$*" in
  *php_handler_id*) [ -f /tmp/plesk-fail-php ] && exit 1 ;;
  *"subscription --update"*"-new-name"*)
    [ -f /tmp/plesk-fail-rename ] && exit 1
    old=$4; new=$6
    [ -f /tmp/plesk-keep-dir ] || mv "/var/www/vhosts/$old" "/var/www/vhosts/$new"
    ;;
esac
exit 0
