<?php
declare(strict_types=1);

// Dependency-free test runner for the WHMCS addon logic:  php tests/php/run.php
// (run under PHP 8.1, the version WHMCS uses:  docker run --rm -v "$PWD":/app -w /app php:8.1-cli php tests/php/run.php)

require __DIR__ . '/../../whmcs/modules/addons/waycloud_ai/lib/autoload.php';
require __DIR__ . '/Fakes.php';

use WayCloud\Ai\Api;
use WayCloud\Ai\Checkout;
use WayCloud\Ai\Document;
use WayCloud\Ai\Hmac;
use WayCloud\Ai\McpNotifier;
use WayCloud\Ai\Settings;

$failures = 0;
$total = 0;

function test(string $name, callable $fn): void
{
    global $failures, $total;
    $total++;
    try {
        $fn();
        echo "  ok    $name\n";
    } catch (Throwable $e) {
        $failures++;
        echo "  FAIL  $name\n        " . $e->getMessage() . "\n";
    }
}

function eq(mixed $expected, mixed $actual, string $what = ''): void
{
    if ($expected !== $actual) {
        throw new RuntimeException(($what !== '' ? "$what: " : '') . 'expected ' . var_export($expected, true) . ', got ' . var_export($actual, true));
    }
}

function yes(bool $cond, string $what): void
{
    if (!$cond) {
        throw new RuntimeException("expected true: $what");
    }
}

const SECRET = '0123456789abcdef0123456789abcdef';
const SESSION = '6f1c2d3e-0000-4000-8000-0123456789ab';

/** @return array{store:MemoryStore, whmcs:FakeWhmcs, checkout:Checkout, notifier:McpNotifier, api:Api, clock:object, posted:object} */
function make(bool $configured = true): array
{
    $store = new MemoryStore();
    $whmcs = new FakeWhmcs();
    $clock = new class { public int $t = 1_700_000_000; };
    $posted = new class { public array $calls = []; public int $status = 200; };
    $settings = new Settings($configured ? ['mcp_url' => 'https://mcp.test/', 'hmac_secret' => SECRET] : []);
    $now = static fn (): int => $clock->t;
    $notifier = new McpNotifier($store, $settings, static function (string $url, array $headers, string $body) use ($posted): int {
        $posted->calls[] = compact('url', 'headers', 'body');
        return $posted->status;
    }, $now);
    $rng = new class { public int $i = 0; };
    $rand = static fn (int $n): string => substr(hash('sha256', 'seed' . $rng->i++, true) . hash('sha256', 'more' . $rng->i, true), 0, $n);
    $checkout = new Checkout($store, $whmcs, $settings, $notifier, $now, $rand);
    $api = new Api($store, $settings, $checkout, $whmcs, $now);
    return compact('store', 'whmcs', 'checkout', 'notifier', 'api', 'clock', 'posted');
}

/** Creates a checkout and returns its token. */
function newToken(array $env, int $pid = 173, string $cycle = 'monthly'): string
{
    $r = $env['checkout']->createFromMcp(['session_id' => SESSION, 'pid' => $pid, 'cycle' => $cycle]);
    preg_match('/t=([A-Za-z0-9_-]+)$/', $r['checkout_url'], $m);
    return $m[1];
}

$valid = [
    'nome' => 'Maria da Silva', 'email' => 'maria@example.com', 'doc_tipo' => 'CPF', 'doc_numero' => '529.982.247-25',
    'telefone' => '(11) 99999-8888', 'senha' => 'S3nha-forte!', 'aceite' => '1', 'website' => '',
];

echo "Document\n";
test('valid and invalid CPF', function () {
    yes(Document::isCpf('529.982.247-25'), 'known valid CPF');
    yes(Document::isCpf('52998224725'), 'digits only');
    yes(!Document::isCpf('529.982.247-24'), 'wrong check digit');
    yes(!Document::isCpf('111.111.111-11'), 'repeated digits');
    yes(!Document::isCpf('123'), 'too short');
});
test('numeric and alphanumeric CNPJ', function () {
    yes(Document::isCnpj('11.222.333/0001-81'), 'known valid numeric CNPJ');
    yes(!Document::isCnpj('11.222.333/0001-82'), 'wrong check digit');
    yes(Document::isCnpj('12.ABC.345/01DE-35'), "Receita's alphanumeric example");
    yes(Document::isCnpj('12abc34501de35'), 'lowercase accepted');
    yes(!Document::isCnpj('00.000.000/0000-00'), 'all zeros');
});
test('format and type dispatch', function () {
    eq('529.982.247-25', Document::format('CPF', '52998224725'));
    eq('11.222.333/0001-81', Document::format('CNPJ', '11222333000181'));
    yes(Document::validate('CPF', '529.982.247-25') && !Document::validate('CNPJ', '529.982.247-25') && !Document::validate('RG', '1'), 'dispatch');
});

echo "HMAC\n";
test('matches the vector generated by the Node service', function () {
    $v = json_decode((string) file_get_contents(__DIR__ . '/../fixtures/hmac-vector.json'), true);
    eq($v['signature'], Hmac::mac($v['secret'], $v['ts'], $v['nonce'], $v['body']), 'signature');
});
test('verify: ok once, then replay', function () {
    $store = new MemoryStore();
    $s = Hmac::sign(SECRET, 'body', 1000, 'nonce-12345');
    eq('ok', Hmac::verify($store, SECRET, $s['ts'], $s['nonce'], $s['signature'], 'body', 1000));
    eq('replay', Hmac::verify($store, SECRET, $s['ts'], $s['nonce'], $s['signature'], 'body', 1000));
});
test('verify: tampered body, wrong secret and bad nonce do not burn the nonce', function () {
    $store = new MemoryStore();
    $s = Hmac::sign(SECRET, 'body', 1000, 'nonce-12345');
    eq('bad_signature', Hmac::verify($store, SECRET, 1000, 'nonce-12345', $s['signature'], 'body!', 1000));
    eq('bad_signature', Hmac::verify($store, str_repeat('x', 40), 1000, 'nonce-12345', $s['signature'], 'body', 1000));
    eq('bad_signature', Hmac::verify($store, SECRET, 1000, 'no', $s['signature'], 'body', 1000));
    eq('ok', Hmac::verify($store, SECRET, 1000, 'nonce-12345', $s['signature'], 'body', 1000));
});
test('verify: 5 minute window and secret guard', function () {
    $store = new MemoryStore();
    $old = Hmac::sign(SECRET, 'b', 1000, 'nonce-aaaaaa');
    eq('expired', Hmac::verify($store, SECRET, 1000, 'nonce-aaaaaa', $old['signature'], 'b', 1301));
    $fresh = Hmac::sign(SECRET, 'b', 1000, 'nonce-bbbbbb');
    eq('ok', Hmac::verify($store, SECRET, 1000, 'nonce-bbbbbb', $fresh['signature'], 'b', 1299));
    $empty = Hmac::sign('', 'b', 1000, 'nonce-cccccc');
    eq('not_configured', Hmac::verify($store, '', 1000, 'nonce-cccccc', $empty['signature'], 'b', 1000), 'empty secret must never verify');
    eq('not_configured', Hmac::verify($store, 'short', 1000, 'nonce-cccccc', 'x', 'b', 1000));
});

echo "Checkout creation (MCP -> addon)\n";
test('creates a link, stores only the token hash, cancels the previous open link', function () {
    $e = make();
    $first = newToken($e);
    $second = newToken($e, 174, 'annually');
    eq('cancelled', $e['store']->checkouts[1]['status'], 'first link cancelled');
    eq('invalid', $e['checkout']->view($first)['state']);
    eq('ready', $e['checkout']->view($second)['state']);
    $row = $e['store']->checkouts[2];
    eq(hash('sha256', $second), $row['token_hash']);
    yes(!str_contains(json_encode($e['store']->checkouts), $second), 'plain token never stored');
    yes((bool) preg_match('/^[a-z2-7]{10}\.sites\.waypreview\.com\.br$/', $row['domain']), 'provisional domain ' . $row['domain']);
    eq(1_700_000_000 + 48 * 3600, $row['expires_at'], 'default 48h expiry');
});
test('rejects bad session, plan and cycle', function () {
    $e = make();
    foreach ([['session_id' => 'nope', 'pid' => 173, 'cycle' => 'monthly', 'code' => 'invalid_session'], ['session_id' => SESSION, 'pid' => 999, 'cycle' => 'monthly', 'code' => 'invalid_plan'], ['session_id' => SESSION, 'pid' => 173, 'cycle' => 'weekly', 'code' => 'invalid_cycle']] as $c) {
        $code = $c['code'];
        unset($c['code']);
        try {
            $e['checkout']->createFromMcp($c);
            throw new RuntimeException("$code not raised");
        } catch (WayCloud\Ai\ApiException $x) {
            eq($code, $x->errorCode);
        }
    }
});

echo "Checkout page states\n";
test('view: invalid, ready, expired, used', function () use ($valid) {
    $e = make();
    eq('invalid', $e['checkout']->view('x')['state']);
    eq('invalid', $e['checkout']->view(str_repeat('a', 43))['state']);
    $t = newToken($e);
    $v = $e['checkout']->view($t);
    eq(['ready', 'Speed BR (teste)', 3590, 'mensal'], [$v['state'], $v['plan_name'], $v['price_cents'], $v['cycle_label']]);
    $e['clock']->t += 48 * 3600 + 1;
    eq('expired', $e['checkout']->view($t)['state']);
    eq('expired', $e['store']->checkouts[1]['status'], 'expiry is persisted');
    eq(false, $e['checkout']->submit($t, $valid)['ok'], 'expired link cannot be submitted');
    $e2 = make();
    $t2 = newToken($e2);
    $e2['checkout']->submit($t2, $valid);
    eq('used', $e2['checkout']->view($t2)['state']);
});
test('annual cycle shows the annual price', function () {
    $e = make();
    eq(38770, $e['checkout']->view(newToken($e, 173, 'annually'))['price_cents']);
});

echo "Checkout submit\n";
test('happy path: client, order, SSO redirect and ids-only webhook payload', function () use ($valid) {
    $e = make();
    $t = newToken($e);
    $r = $e['checkout']->submit($t, $valid);
    eq(true, $r['ok'], 'ok');
    eq('https://app.test/sso/abc', $r['redirect']);

    [$name, $client] = $e['whmcs']->calls[0];
    eq('addClient', $name);
    eq(['Maria', 'da Silva', 'maria@example.com', 'BR', '+55.11999998888'], [$client['firstname'], $client['lastname'], $client['email'], $client['country'], $client['phonenumber']]);
    eq(['Não informado', 'Não informado', 'SP', '00000-000'], [$client['address1'], $client['city'], $client['state'], $client['postcode']], 'address defaults');
    eq([11 => 'CPF', 12 => '529.982.247-25', 13 => '(11) 99999-8888'], unserialize(base64_decode($client['customfields'])), 'custom fields by id, including the required "Celular"');

    [, $order] = $e['whmcs']->calls[1];
    eq(['clientId' => 100, 'pid' => 173, 'cycle' => 'monthly', 'paymentMethod' => 'efipix'], array_intersect_key($order, array_flip(['clientId', 'pid', 'cycle', 'paymentMethod'])));
    yes((bool) preg_match('/\.sites\.waypreview\.com\.br$/', $order['domain']), 'provisional domain used');
    eq(['sso', [100, 'viewinvoice.php?id=1500']], $e['whmcs']->calls[2]);

    $c = $e['store']->checkouts[1];
    eq(['ordered', 100, 500, 1500, 2500], [$c['status'], $c['client_id'], $c['order_id'], $c['invoice_id'], $c['service_id']]);

    eq(1, count($e['posted']->calls), 'one signed webhook sent');
    $sent = $e['posted']->calls[0];
    eq('https://mcp.test/webhooks/whmcs', $sent['url']);
    $body = json_decode($sent['body'], true);
    eq('order.created', $body['event']);
    eq([SESSION, 1, 173, 'monthly', 500, 1500, 2500], [$body['data']['session_id'], $body['data']['checkout_id'], $body['data']['plan_pid'], $body['data']['cycle'], $body['data']['whmcs_order_id'], $body['data']['whmcs_invoice_id'], $body['data']['whmcs_service_id']]);
});
test('privacy: no e-mail, CPF, phone or password in webhooks or logs', function () use ($valid) {
    $e = make();
    $e['checkout']->submit(newToken($e), $valid);
    $dump = json_encode([$e['posted']->calls, $e['store']->outbox, $e['store']->log]);
    foreach (['maria@example.com', '529.982.247-25', '52998224725', '99999-8888', '999998888', 'S3nha-forte!', 'Maria'] as $secret) {
        yes(!str_contains($dump, $secret), "leaked: $secret");
    }
});
test('validation errors, and nothing is created', function () use ($valid) {
    $e = make();
    $t = newToken($e);
    $bad = ['nome' => 'Maria', 'email' => 'nao-e-email', 'doc_tipo' => 'CPF', 'doc_numero' => '111.111.111-11', 'telefone' => '123', 'senha' => 'curta', 'aceite' => '', 'website' => ''];
    $r = $e['checkout']->submit($t, $bad);
    eq(false, $r['ok']);
    eq(['aceite', 'doc_numero', 'email', 'nome', 'senha', 'telefone'], (function () use ($r) { $k = array_keys($r['errors']); sort($k); return $k; })());
    eq([], $e['whmcs']->calls, 'WHMCS untouched');
    eq('ready', $e['checkout']->view($t)['state'], 'link still usable');
});
test('honeypot: a bot is answered as if the link were gone', function () use ($valid) {
    $e = make();
    $r = $e['checkout']->submit(newToken($e), ['website' => 'http://spam'] + $valid);
    eq([false, 'invalid'], [$r['ok'], $r['state']]);
    eq([], $e['whmcs']->calls);
});
test('existing e-mail: asks to log in, never attaches an order to someone else\'s account', function () use ($valid) {
    $e = make();
    $e['whmcs']->clients['maria@example.com'] = 42;
    $r = $e['checkout']->submit(newToken($e), $valid);
    eq(false, $r['ok']);
    yes(isset($r['errors']['email']) && $r['login_url'] === 'https://app.test/clientarea.php', 'login hint');
    eq([], $e['whmcs']->calls, 'no client, no order');
});
test('logged-in customer: only consent needed, order goes to their account', function () use ($valid) {
    $e = make();
    $t = newToken($e);
    eq(false, $e['checkout']->submit($t, ['aceite' => ''], 42)['ok'], 'consent still required');
    $r = $e['checkout']->submit($t, ['aceite' => '1'], 42);
    eq(true, $r['ok']);
    $names = array_column($e['whmcs']->calls, 0);
    eq(['addOrder', 'sso'], $names, 'no addClient');
    eq(42, $e['whmcs']->calls[0][1]['clientId']);
});
test('WHMCS refuses the password / duplicate e-mail: friendly errors, nothing leaked', function () use ($valid) {
    $e = make();
    $e['whmcs']->failAddClient = 'Password strength is too low';
    $r = $e['checkout']->submit(newToken($e), $valid);
    yes(isset($r['errors']['senha']), 'password message');
    $e2 = make();
    $e2['whmcs']->failAddClient = 'A user already exists with that email address';
    $r2 = $e2['checkout']->submit(newToken($e2), $valid);
    yes(isset($r2['errors']['email']) && $r2['login_url'] !== null, 'email exists');
    $e3 = make();
    $e3['whmcs']->failAddClient = 'SQLSTATE[HY000] secret internal detail';
    $r3 = $e3['checkout']->submit(newToken($e3), $valid);
    yes(!str_contains(json_encode($r3), 'SQLSTATE'), 'raw error not shown to the customer');
    eq(1, count($e3['whmcs']->alerts), 'admin alerted');
});
test('order failure: rolls back to a retryable state and the retry does not create a second client', function () use ($valid) {
    $e = make();
    $t = newToken($e);
    $e['whmcs']->failAddOrder = 'boom';
    $r = $e['checkout']->submit($t, $valid);
    eq(false, $r['ok']);
    eq('client_created', $e['store']->checkouts[1]['status']);
    eq(100, $e['store']->checkouts[1]['client_id']);
    $e['whmcs']->failAddOrder = null;
    $r2 = $e['checkout']->submit($t, $valid); // same browser, not logged in, e-mail now exists in WHMCS
    eq(true, $r2['ok'], 'retry works');
    eq(1, count(array_filter($e['whmcs']->calls, fn ($c) => $c[0] === 'addClient')), 'only one client created');
});
test('double submit and race: exactly one order', function () use ($valid) {
    $e = make();
    $t = newToken($e);
    $e['checkout']->submit($t, $valid);
    $again = $e['checkout']->submit($t, $valid);
    eq([false, 'used'], [$again['ok'], $again['state']]);
    eq(1, count(array_filter($e['whmcs']->calls, fn ($c) => $c[0] === 'addOrder')));

    $e2 = make();
    $t2 = newToken($e2);
    $e2['store']->updateCheckout(1, ['status' => 'ordering', 'client_id' => 7]); // another request already claimed it
    eq('used', $e2['checkout']->submit($t2, $valid)['state']);
    eq([], $e2['whmcs']->calls);
});
test('true concurrency: a request that lost the claim creates no order', function () use ($valid) {
    $e = make();
    $t = newToken($e);
    // While our request is inside addClient, another request claims the checkout and starts ordering.
    $e['whmcs']->afterAddClient = fn () => $e['store']->updateCheckout(1, ['status' => 'ordering']);
    $r = $e['checkout']->submit($t, $valid);
    eq([false, 'used'], [$r['ok'], $r['state']]);
    eq(0, count(array_filter($e['whmcs']->calls, fn ($c) => $c[0] === 'addOrder')), 'no second order');
});
test('the "Celular" field is filled when it exists and simply skipped when it does not', function () use ($valid) {
    $e = make();
    unset($e['whmcs']->customFields['Celular']);
    eq(true, $e['checkout']->submit(newToken($e), $valid)['ok']);
    eq([11 => 'CPF', 12 => '529.982.247-25'], unserialize(base64_decode($e['whmcs']->calls[0][1]['customfields'])));
    eq('(11) 9999-8888', Checkout::phoneDisplay('1199998888'), '10-digit numbers keep the landline format');
    eq('(11) 99999-8888', Checkout::phoneDisplay('+55 11 99999-8888'));
    eq(null, Checkout::phoneDisplay('123'));
});
test('diagnostics flag a required client field the checkout does not fill', function () {
    $e = make();
    $names = static fn (array $checks): array => array_column(array_filter($checks, static fn (array $c): bool => !$c['ok']), 'label');
    $ok = WayCloud\Ai\Diagnostics::run($e['store'], $e['whmcs'], new Settings(['hmac_secret' => SECRET, 'mcp_url' => 'https://mcp.test']));
    yes(!in_array('Campos obrigatórios de cliente', $names($ok), true), 'Celular and CPF/CNPJ are handled');
    $e['whmcs']->requiredFields = ['CPF/CNPJ', 'Celular', 'RG'];
    $bad = WayCloud\Ai\Diagnostics::run($e['store'], $e['whmcs'], new Settings(['hmac_secret' => SECRET, 'mcp_url' => 'https://mcp.test']));
    yes(in_array('Campos obrigatórios de cliente', $names($bad), true), 'RG is not handled');
    yes(str_contains(json_encode($bad, JSON_UNESCAPED_UNICODE), 'RG'), 'names the field');
});
test('missing custom fields: admin alert and a friendly message', function () use ($valid) {
    $e = make();
    $e['whmcs']->customFields = [];
    $r = $e['checkout']->submit(newToken($e), $valid);
    yes(isset($r['errors']['_form']) && count($e['whmcs']->alerts) === 1, 'alert');
    eq([], $e['whmcs']->calls);
});
test('SSO failure falls back to the invoice URL', function () use ($valid) {
    $e = make();
    $e['whmcs']->sso = null;
    eq('https://app.test/viewinvoice.php?id=1500', $e['checkout']->submit(newToken($e), $valid)['redirect']);
});

echo "WHMCS hooks\n";
function ordered(array $valid): array
{
    $e = make();
    $e['checkout']->submit(newToken($e), $valid);
    $e['posted']->calls = [];
    return $e;
}
$events = static fn (array $e): array => array_map(static fn (array $c): string => json_decode($c['body'], true)['event'], $e['posted']->calls);
test('InvoicePaid: order.paid once, idempotent, ignores other invoices', function () use ($valid, $events) {
    $e = ordered($valid);
    $e['checkout']->onInvoicePaid(999);
    $e['checkout']->onInvoicePaid(1500);
    $e['checkout']->onInvoicePaid(1500);
    eq(['order.paid'], $events($e));
    eq('paid', $e['store']->checkouts[1]['status']);
});
test('AfterModuleCreate: service.active carries the domain and server id', function () use ($valid, $events) {
    $e = ordered($valid);
    $e['checkout']->onInvoicePaid(1500);
    $e['checkout']->onModuleCreated(2500, ['server_id' => 18]);
    $e['checkout']->onModuleCreated(2500, ['server_id' => 18]);
    eq(['order.paid', 'service.active'], $events($e));
    $d = json_decode($e['posted']->calls[1]['body'], true)['data'];
    eq([2500, 18, $e['store']->checkouts[1]['domain']], [$d['whmcs_service_id'], $d['whmcs_server_id'], $d['domain']]);
    eq('active', $e['store']->checkouts[1]['status']);
});
test('provisioning before InvoicePaid still emits paid, then active, in order', function () use ($valid, $events) {
    $e = ordered($valid);
    $e['checkout']->onModuleCreated(2500, ['server_id' => 18]);
    $e['checkout']->onInvoicePaid(1500);
    eq(['order.paid', 'service.active'], $events($e));
});
test('AfterModuleCreateFailed: failed status, no raw reason in the webhook, admin alerted', function () use ($valid, $events) {
    $e = ordered($valid);
    $e['checkout']->onInvoicePaid(1500);
    $e['checkout']->onModuleCreateFailed(2500, 'Plesk: quota exceeded for /var/www secret-detail');
    eq(['order.paid', 'service.failed'], $events($e));
    yes(!str_contains($e['posted']->calls[1]['body'], 'secret-detail'), 'reason stays out of the webhook');
    eq('failed', $e['store']->checkouts[1]['status']);
    eq(1, count($e['whmcs']->alerts));
    $e['checkout']->onModuleCreated(2500); // a late success never resurrects a failed checkout
    eq('failed', $e['store']->checkouts[1]['status']);
});
test('hooks ignore services that did not come from the AI flow', function () use ($valid, $events) {
    $e = ordered($valid);
    $e['checkout']->onModuleCreated(31337);
    $e['checkout']->onModuleCreateFailed(31337, 'x');
    eq([], $events($e));
    eq([], $e['whmcs']->alerts);
});

echo "Outbox\n";
test('not configured: events wait in the outbox, nothing is sent', function () use ($valid) {
    $e = make(false);
    $e['checkout']->submit(newToken($e), $valid);
    eq(0, count($e['posted']->calls));
    eq(1, $e['store']->pendingOutbox());
});
test('signed request verifies on the receiving side', function () use ($valid) {
    $e = make();
    $e['checkout']->submit(newToken($e), $valid);
    $c = $e['posted']->calls[0];
    $h = [];
    foreach ($c['headers'] as $line) {
        [$k, $v] = explode(': ', $line, 2);
        $h[strtolower($k)] = $v;
    }
    eq('ok', Hmac::verify(new MemoryStore(), SECRET, (int) $h['x-waycloud-timestamp'], $h['x-waycloud-nonce'], $h['x-waycloud-signature'], $c['body'], 1_700_000_000));
    eq('application/json', $h['content-type']);
});
test('failure keeps the event and retries with backoff until it is delivered', function () use ($valid) {
    $e = make();
    $e['posted']->status = 500;
    $e['checkout']->submit(newToken($e), $valid);
    eq(1, $e['store']->pendingOutbox());
    eq(1, $e['store']->outbox[1]['attempts']);
    eq(1_700_000_000 + 60, $e['store']->outbox[1]['next_attempt_at'], 'backoff 30s * 2^1');
    eq(0, $e['notifier']->flush(), 'not due yet: nothing sent');
    $e['clock']->t += 61;
    $e['posted']->status = 200;
    eq(1, $e['notifier']->flush(), 'delivered on retry');
    eq(0, $e['store']->pendingOutbox());
});
test('network error (status 0) is a failure too, backoff is capped at 1 hour', function () use ($valid) {
    $e = make();
    $e['posted']->status = 0;
    $e['checkout']->submit(newToken($e), $valid);
    eq(1, $e['store']->pendingOutbox());
    $e['store']->markEventFailed(1, 20, 0);
    $e['notifier']->flush();
    eq(1_700_000_000 + 3600, $e['store']->outbox[1]['next_attempt_at']);
});

echo "Addon API\n";
$call = static function (array $e, array $body, ?callable $tamper = null, string $method = 'POST'): array {
    $raw = json_encode($body);
    $s = Hmac::sign(SECRET, $raw, $e['clock']->t, bin2hex(random_bytes(8)));
    $h = ['x-waycloud-timestamp' => (string) $s['ts'], 'x-waycloud-nonce' => $s['nonce'], 'x-waycloud-signature' => $s['signature']];
    if ($tamper) {
        [$h, $raw] = $tamper($h, $raw);
    }
    return $e['api']->handle($method, $h, $raw);
};
test('rejects anything that is not a valid signed POST, without saying why', function () use ($call) {
    $e = make();
    eq(405, $call($e, ['action' => 'ping'], null, 'GET')[0]);
    eq([401, ['error' => 'unauthorized']], $call($e, ['action' => 'ping'], fn ($h, $r) => [[], $r]), 'no headers');
    eq([401, ['error' => 'unauthorized']], $call($e, ['action' => 'ping'], fn ($h, $r) => [$h, $r . ' ']), 'tampered body');
    eq([401, ['error' => 'unauthorized']], $call($e, ['action' => 'ping'], fn ($h, $r) => [['x-waycloud-timestamp' => (string) ($e['clock']->t - 400)] + $h, $r]), 'stale timestamp is not enough');
    $unconfigured = make(false);
    eq(401, $unconfigured['api']->handle('POST', [], '{"action":"ping"}')[0], 'no secret configured');
});
test('a rejected request is still a 401 when the log itself fails (tables not created yet)', function () {
    $e = make();
    $failing = new class extends MemoryStore {
        public function logEvent(string $type, ?string $ref, array $data, int $now): void
        {
            throw new RuntimeException('table mod_waycloud_events does not exist');
        }
    };
    $api = new Api($failing, new Settings(['hmac_secret' => '']), $e['checkout'], $e['whmcs'], static fn (): int => 1_700_000_000);
    eq([401, ['error' => 'unauthorized']], $api->handle('POST', [], '{"action":"ping"}'));
});
test('replay of a valid request is refused', function () use ($call) {
    $e = make();
    $raw = json_encode(['action' => 'ping']);
    $s = Hmac::sign(SECRET, $raw, $e['clock']->t, 'fixednonce123');
    $h = ['x-waycloud-timestamp' => (string) $s['ts'], 'x-waycloud-nonce' => $s['nonce'], 'x-waycloud-signature' => $s['signature']];
    eq(200, $e['api']->handle('POST', $h, $raw)[0]);
    eq(401, $e['api']->handle('POST', $h, $raw)[0]);
});
test('ping, plans, create_checkout, unknown action and invalid json', function () use ($call) {
    $e = make();
    eq([200, ['ok' => true]], $call($e, ['action' => 'ping']));
    [$s, $plans] = $call($e, ['action' => 'plans']);
    eq(200, $s);
    eq([['static', 173], ['php', 174]], array_map(fn ($p) => [$p['type'], $p['pid']], $plans['plans']));
    [$s, $r] = $call($e, ['action' => 'create_checkout', 'session_id' => SESSION, 'pid' => 173, 'cycle' => 'annually']);
    eq(200, $s);
    yes(str_starts_with($r['checkout_url'], 'https://app.test/index.php?m=waycloud_ai&t='), 'url');
    eq([422, ['error' => 'invalid_plan']], $call($e, ['action' => 'create_checkout', 'session_id' => SESSION, 'pid' => 1, 'cycle' => 'monthly']));
    eq([400, ['error' => 'unknown_action']], $call($e, ['action' => 'drop_tables']));
    $raw = 'not json';
    $sig = Hmac::sign(SECRET, $raw, $e['clock']->t, 'nonce-json-1');
    eq(400, $e['api']->handle('POST', ['x-waycloud-timestamp' => (string) $sig['ts'], 'x-waycloud-nonce' => $sig['nonce'], 'x-waycloud-signature' => $sig['signature']], $raw)[0]);
});

echo "\n" . ($total - $failures) . "/$total passed\n";
exit($failures === 0 ? 0 : 1);
